classes:
  - kapitan.kube
  - kapitan.generators.kubernetes

parameters:
  scripts: []
  docs:
    - templates/docs/README.md 
  manifests: []
  kapitan:
    compile:
      - output_path: docs
        input_type: jinja2
        input_paths: ${docs}
      - output_path: scripts
        input_type: jinja2
        input_paths: ${scripts}
    vars:
      target: ${target_name}
