apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sock-shop-prod
  labels:
    name: global
  name: global
  namespace: prod-sockshop
spec:
  backend:
    service:
      name: frontend
      port: 80
  tls:
    - hosts:
        - sockshop.kapicorp.com
      secretName: sockshop.kapicorp.com
