classes:
  - common
  - projects.kapitan-demo.kubernetes.demo
  - applications.sock-shop

parameters:
  components:
    frontend:
      service:
        type: NodePort
  generators:
    kubernetes:
      secrets:
        sockshop.kapicorp.com:
          type: kubernetes.io/tls
          data:
            tls.crt:
              value: CERTIFICATE
            tls.key:
              value: KEY
  ingresses:
    global:
      annotations:
        kubernetes.io/ingress.global-static-ip-name: sock-shop-prod
      domains:
      - sockshop.kapicorp.com
      default_backend:
        name: frontend
        port: 80
      tls:
      - hosts:
          - sockshop.kapicorp.com
        secretName: sockshop.kapicorp.com