apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app: vault-server
  name: vault-server
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-server
  serviceName: vault-server
  template:
    metadata:
      labels:
        app: vault-server
    spec:
      containers:
        - args:
            - '/usr/local/bin/docker-entrypoint.sh vault server -config=/vault/config/config.hcl

              '
          command:
            - /bin/sh
            - -ec
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SKIP_CHOWN
              value: 'true'
            - name: SKIP_SETCAP
              value: 'true'
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: VAULT_API_ADDR
              value: http://$(POD_IP):8200
            - name: VAULT_CLUSTER_ADDR
              value: https://$(HOSTNAME).vault-server:8201
            - name: VAULT_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VAULT_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: vault:1.4.0
          imagePullPolicy: IfNotPresent
          name: vault-server
          ports:
            - containerPort: 8200
              name: http
              protocol: TCP
            - containerPort: 8202
              name: http-rep
              protocol: TCP
            - containerPort: 8201
              name: https-internal
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -ec
                - vault status -tls-skip-verify
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /vault/config
              name: config
              readOnly: true
            - mountPath: /vault/data
              name: datadir
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: vault-server
          name: config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        labels:
          name: datadir
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-server
  name: vault-server
  namespace: vault
spec:
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: http
    - name: http-rep
      port: 8202
      protocol: TCP
      targetPort: http-rep
    - name: https-internal
      port: 8201
      protocol: TCP
      targetPort: https-internal
  selector:
    app: vault-server
  sessionAffinity: None
  type: LoadBalancer
