parameters:
  components:
    vault-server:
      type: statefulset
      image: vault:1.4.0
      service:
        type: LoadBalancer
      ports:
        http:
          service_port: 8200
        https-internal:
          service_port: 8201
        http-rep:
          service_port: 8202
      env:
        HOST_IP:
          fieldRef:
            fieldPath: status.hostIP
        POD_IP:
          fieldRef:
            fieldPath: status.podIP
        VAULT_K8S_POD_NAME:
          fieldRef:
            fieldPath: metadata.name
        VAULT_K8S_NAMESPACE:
          fieldRef:
            fieldPath: metadata.namespace
        VAULT_ADDR: "http://127.0.0.1:8200"
        VAULT_API_ADDR: "http://$(POD_IP):8200"
        SKIP_CHOWN: "true"
        SKIP_SETCAP: "true"
        HOSTNAME:
          fieldRef:
            fieldPath: metadata.name
        VAULT_CLUSTER_ADDR: "https://$(HOSTNAME).vault-server:8201"
      command:
        - "/bin/sh"
        - "-ec"
      args:
        - |
          /usr/local/bin/docker-entrypoint.sh vault server -config=/vault/config/config.hcl
      healthcheck:
        type: command
        command: ["/bin/sh", "-ec", "vault status -tls-skip-verify"]
        probes: ['readiness']
        timeout_seconds: 5
      config_maps:
        config:
          mount: /vault/config
          data:
            extraconfig-from-values.hcl:
              template: components/hashicorp/vault/config.hcl
              values: {}
      volume_mounts:
        datadir:
          mountPath: /vault/data
      volume_claims:
        datadir:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi